language: node_js
node_js:
  "10.12.0"
dist: trusty
sudo: false
addons:
  chrome: stable
before_script:
  npm run start
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  directories:
    "node_modules"
